### ISSUE TITLE
Search is not working.

### ISSUE THREAD

**Issue by MSZ991** [johndavemanuel/yts-movies#1]
Thank you for creating this wonderful app. But Search is not working,its not showing any thing. Only blank page is showing as a result.

**Comment by johndavemanuel** [comment]
Hi @MSZ991 
It is working fine on my side,

What search is not working, simple or advanced?
What are you trying to search?
Are you using the latest commit code? I think I fix an error in search in my last commit

**Comment by MSZ991** [comment]
Yes!! I downloaded the apk last night.Please look into this matter.
![SS_1](https://user-images.githubusercontent.com/14855029/59552163-d6a02380-8f9c-11e9-97b0-914e353dcc69.jpeg)
![SS_2](https://user-images.githubusercontent.com/14855029/59552165-d9027d80-8f9c-11e9-9c97-4ce3a360bb9b.jpeg)

**Comment by johndavemanuel** [comment]
I will check on my side and let you know, I think the last apk build was buggy and not the latest code

**Comment by johndavemanuel** [comment]
I have updated the source code and apk,
